const colors = {
  background: '#050505',
  surface: '#0a0a0a',
  surfaceInput: '#111113',
  surfaceRaised: '#18181b',
  surfaceOverlay: 'rgba(24,24,27,0.96)',
  border: '#27272a',
  borderSubtle: 'rgba(255,255,255,0.10)',
  text: '#fafafa',
  textMuted: '#a1a1aa',
  textSubtle: '#71717a',
  primary: '#8b5cf6',
  primaryHover: '#a78bfa',
  primarySubtle: 'rgba(139,92,246,0.16)',
  primaryWash: 'rgba(139,92,246,0.12)',
  primaryBadge: 'rgba(139,92,246,0.14)',
  primaryBorder: 'rgba(139,92,246,0.32)',
  primaryBorderStrong: 'rgba(139,92,246,0.75)',
  success: '#34d399',
  successSubtle: 'rgba(16,185,129,0.14)',
  successWash: 'rgba(16,185,129,0.11)',
  successBorder: 'rgba(16,185,129,0.22)',
  successBorderStrong: 'rgba(16,185,129,0.34)',
  warning: '#fbbf24',
  warningSubtle: 'rgba(245,158,11,0.14)',
  warningWash: 'rgba(245,158,11,0.12)',
  warningBorder: 'rgba(245,158,11,0.22)',
  danger: '#f87171',
  dangerSubtle: 'rgba(239,68,68,0.14)',
  dangerWash: 'rgba(239,68,68,0.12)',
  dangerBorder: 'rgba(239,68,68,0.22)',
  neutralWash: 'rgba(113,113,122,0.14)',
  neutralBorder: 'rgba(161,161,170,0.18)',
  control: 'rgba(255,255,255,0.08)',
  controlPanel: 'rgba(255,255,255,0.055)',
  controlBorder: 'rgba(255,255,255,0.07)',
  controlPressed: 'rgba(255,255,255,0.14)',
  white: '#ffffff',
  skeleton: '#27272a',
};

export const brand = {
  background: colors.background,
  surface: colors.surface,
  surfaceRaised: colors.surfaceRaised,
  border: colors.border,
  text: colors.text,
  muted: colors.textMuted,
  primary: colors.primary,
  colors,
  space: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    xl: 24,
    '2xl': 28,
    full: 999,
  },
  typography: {
    kicker: { fontSize: 11, fontWeight: '800' as const, letterSpacing: 0 },
    title: { fontSize: 32, fontWeight: '900' as const, letterSpacing: 0 },
    body: { fontSize: 15, lineHeight: 22 },
    label: { fontSize: 13, fontWeight: '800' as const },
    navTitle: { fontSize: 17, fontWeight: '800' as const },
    listTitle: { fontSize: 16, fontWeight: '800' as const },
    sectionTitle: { fontSize: 16, fontWeight: '900' as const },
    trackTitle: { fontSize: 15, fontWeight: '700' as const },
    buttonLabel: { fontSize: 14, fontWeight: '900' as const },
    badge: { fontSize: 10, fontWeight: '900' as const },
    tinyBadge: { fontSize: 9, fontWeight: '900' as const },
    caption: { fontSize: 12, lineHeight: 16 },
    status: { fontSize: 13, lineHeight: 19 },
  },
  layout: {
    emptyStatePadding: 36,
    listArtworkSize: 44,
    miniPlayerClearance: 108,
    miniPlayerArtworkSize: 54,
    miniPlayerRowMinHeight: 82,
    navBarHorizontalPadding: 0,
    navBarMinHeight: 60,
    playlistAddIconSize: 28,
    playlistChipWidth: 150,
    serverCardMinHeight: 74,
    syncDotSize: 7,
    skeleton: {
      badge: { width: 74, height: 17 },
      duration: { width: 34, height: 12 },
      meta: { width: 62, height: 11 },
      title: { width: 104, height: 13 },
      trackMetaHeight: 12,
      trackTitleHeight: 15,
    },
  },
  control: {
    buttonHeightCompact: 42,
    buttonHeightPrimary: 48,
    buttonHeightSmall: 38,
    deleteButtonSize: 40,
    iconButtonSize: 38,
    navButtonSize: 48,
    playButtonSize: 48,
  },
  icon: {
    pauseGap: 5,
    transportGap: 3,
    trashCanRadius: 3,
    trashLidRadius: 2,
  },
  elevation: {
    floating: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.38,
      shadowRadius: 28,
      elevation: 18,
    },
    primary: {
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.38,
      shadowRadius: 14,
      elevation: 10,
    },
  },
  components: {
    page: {
      backgroundColor: colors.background,
    },
    surfaceCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    raisedCard: {
      backgroundColor: colors.surfaceRaised,
      borderWidth: 1,
      borderColor: colors.border,
    },
    inputSurface: {
      backgroundColor: colors.surfaceInput,
      borderWidth: 1,
      borderColor: colors.border,
    },
    activeSurface: {
      backgroundColor: colors.primaryWash,
      borderColor: colors.primaryBorder,
    },
    selectedSurface: {
      backgroundColor: colors.primaryBadge,
      borderColor: colors.primaryBorderStrong,
    },
    centeredControl: {
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    primaryButton: {
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: colors.primary,
    },
    softPrimaryButton: {
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: colors.primarySubtle,
      borderWidth: 1,
      borderColor: colors.primaryBorder,
    },
    statusBadge: {
      alignSelf: 'flex-start' as const,
      overflow: 'hidden' as const,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    disabledButton: {
      opacity: 0.42,
    },
    pressedSurface: {
      backgroundColor: colors.controlPressed,
      transform: [{ scale: 0.985 }],
    },
    pressedControl: {
      backgroundColor: colors.controlPressed,
      transform: [{ scale: 0.94 }],
    },
    pressedPrimary: {
      backgroundColor: colors.primaryHover,
      transform: [{ scale: 0.95 }],
    },
  },
} as const;
